version: '3'

services:
  dotnet_app:
    container_name: taskninja_dotnet_app
    build:
      context: .
      dockerfile: TaskNinjaHub.MachineLearning.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8090:8080"

  nginx:
    image: nginx:latest
    container_name: taskninja_nginx
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dotnet_app
