version: '3'

services:
  dotnet_app:
    container_name: taskninja_dotnet_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8090:8080"
      - "8091:8081"
      - "5000:5000"
    depends_on:
      - python_app

  python_app:
    container_name: taskninja_python_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    container_name: taskninja_nginx
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dotnet_app
      - python_app
