version: '3'

services:
  dotnet_app:
    container_name: taskninja_dotnet_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "401:8080"
      - "402:8081"
      - "403:5000"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: taskninja_nginx
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dotnet_app