version: '3'
services:
  notify:
    container_name: machine
    build:
      context: ../
      dockerfile: ./TaskNinjaHub.NotificationService.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "403:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock